### ISSUE TITLE
epicR: Lower tail FEV1 values to be corrected

### ISSUE THREAD

**Issue by aminadibi** [aminadibi/epicR#23]
FEV1 values decline too much on the lower tail. Need to plateau them at a certain threshold.

**Comment by aminadibi** [comment]
@shahzadg Shahzad can you please let me know at what value should I plateau the low tail of FEV1. Was it 0.8? Is it the same number for everyone?

Thanks

**Comment by shahzadg** [comment]
` RAND_TAIL_FEV1_t = sqrt(0.1845)*RandNormal()+ 0.827;`

**Comment by aminadibi** [comment]
implemented in epicR as (*ag).fev1_tail.

**Comment by aminadibi** [comment]
Fixed in epicR v0.5.0
