### ISSUE TITLE
FEV1 Seems to be increasing for some people! :O

### ISSUE THREAD

**Issue by aminadibi** [aminadibi/epicR#30]
Look:

It could be related  to the other issues where FEV1 for a new non-COPD agent is not reset. 

![image](https://user-images.githubusercontent.com/20497354/29788385-41a14076-8be7-11e7-9de2-5f0f63c019bd.png)

**Comment by shahzadg** [comment]
Could you check the percentage of the patients who experience the increase in their lung function? 
I could see the increase in FEV1 in EPIC -POHEM  but just in a very small percentage (I also need to check the percentage)

**Comment by aminadibi** [comment]
Yeah seems to be a small group.
