### ISSUE TITLE
high number of Exacerbations  

### ISSUE THREAD

**Issue by shahzadg** [aminadibi/epicR#36]
```
>  log_exac_hazard =  ( has_copd ==TRUE && sex== MALE )   ? intercept_exac_hazard + 0.04082*0.1*(integer_age)+(copd_stage == COPD_STAGE2)*COPD_exac_hazard[copd_stage]+(copd_stage == COPD_STAGE3 || copd_stage == COPD_STAGE4 )*COPD_exac_hazard[copd_stage]+ x_rate_exacerbation_random_effect: 
> 	                 ( has_copd ==TRUE && sex== FEMALE ) ? intercept_exac_hazard + 0.04082*0.1*(integer_age)+(copd_stage == COPD_STAGE2)*COPD_exac_hazard[copd_stage]+(copd_stage == COPD_STAGE3 || copd_stage == COPD_STAGE4 )*COPD_exac_hazard[copd_stage]+ x_rate_exacerbation_random_effect: -10000;
> 
```

**Comment by shahzadg** [comment]
COPD stages coefficentts
no copd    mild          moderate       severe      very severe 
0	           0	               0.6	         1.02	   1.02
intercept_exac_hazard= -1.280

**Comment by aminadibi** [comment]
Assumptions: exac rates per GOLD should be 0.15 of Hoogendoorn values

**Comment by aminadibi** [comment]
Based on the above assumption, the issue has been resolved in [https://github.com/aminadibi/epicR/commit/855265e25e930633f7266d6dce0248f1727787c7](https://github.com/aminadibi/epicR/commit/855265e25e930633f7266d6dce0248f1727787c7)
