### ISSUE TITLE
getting symptoms regression values and correlation matrix for random effects

### ISSUE THREAD

**Issue by aminadibi** [aminadibi/epicR#64]
Need to recreate regression equations for symptoms and calculate covariance matrix for random effects of symptoms so we can account for correlations between them

**Comment by aminadibi** [comment]
Kate will give us 4 random effects. At the annual event, we update symptoms of patients. We need multivariate sampling in C code.

**Comment by KateJohnson** [comment]
I need to determine the logit for each patient (COPD+non-COPD) of experiencing each symptom. Then determine the covariance matrix of the p's (4x4 matrix). 
Include age, sex, smoking status, pack-years and FEV1 as covariates in the models.
