### ISSUE TITLE
Implement mvrnorm generator in C as a generic function

### ISSUE THREAD

**Issue by KateJohnson** [aminadibi/epicR#69]

**Comment by aminadibi** [comment]
You can do mvrnorm in R, buffer a big number, and pass it to C, like what we do with runif.

**Comment by aminadibi** [comment]
Rcpp Armadillo seems to be able to do this, as per [http://gallery.rcpp.org/articles/simulate-multivariate-normal/](http://gallery.rcpp.org/articles/simulate-multivariate-normal/)

Added the function and required dependencies to epicR.

**Comment by aminadibi** [comment]
Done in https://github.com/aminadibi/epicR/commit/0f56d7f170d54e5207fda0b946fac737a3aab4ac
